# A github workflow monitoring the latest release of just-the-docs
# This workflow is triggered on a schedule
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
name: Update JTD

on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:
    # manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get latest release information
        id: latest-release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          owner: just-the-docs
          repo: just-the-docs
          excludes: prerelease, draft

      - name: Update Gemfile
        run: |
          VERSION=$(echo ${{steps.latest-release.outputs.release}} | sed -e 's/v//')
          bundle remove just-the-docs
          bundle add just-the-docs --version "~> ${VERSION}"

      - name: Create PR
        uses: peter-evans/create-pull-request@v5.0.1
        with:
          commit-message: "chore[deps]: Update just-the-docs to ${{ steps.latest-release.outputs.release }}"
          title: "auto: Update `just-the-docs` to `${{ steps.latest-release.outputs.release }}`"
          body: |
            Update `just-the-docs` to `${{ steps.latest-release.outputs.release }}`

            This is an automated pull request.

            ---
            ${{ steps.latest-release.outputs.description }}

          branch: update/just-the-docs
          delete-branch: true
          add-paths: |
            Gemfile
            Gemfile.lock
          token: ${{ secrets.GITHUB_TOKEN }}