# A github workflow monitoring the latest release of just-the-docs
# This workflow is triggered on a schedule
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
name: Update JTD

on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:
    # manually

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: false # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems

      - name: Get latest release information
        id: latest-release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          owner: just-the-docs
          repo: just-the-docs
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Gemfile
        run: |
          VERSION=$(echo ${{steps.latest-release.outputs.release}} | sed -e 's/v//')
          bundle remove just-the-docs
          bundle add just-the-docs --version "~> ${VERSION}"

      - name: Create PR
        uses: peter-evans/create-pull-request@v5.0.1
        continue-on-error: true
        with:
          commit-message: "chore[deps]: Update just-the-docs to ${{ steps.latest-release.outputs.release }}"
          title: "auto: Update `just-the-docs` to `${{ steps.latest-release.outputs.release }}`"
          body: |
            Update `just-the-docs` to `${{ steps.latest-release.outputs.release }}`

            This is an automated pull request.

            ---
            ${{ steps.latest-release.outputs.description }}

          branch: update/just-the-docs
          delete-branch: true
          add-paths: |
            Gemfile
            Gemfile.lock
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue on Failed workflow
        uses: dacbd/create-issue-action@v1.2.1
        if: ${{ failure() }}
        with:
          token: ${{ github.token }}
          title: An update failed - more permissions required
          body: |
            Hello there!

            This issue was created automatically to guide you on your way to solve a small permission problem. Don't worry, it's not complicated.

            One of the integrated workflows (`Update JTD`) tried to open a pull-request with an update to a newer version of the just-the-docs-theme. Unfortunately the default repository setting prevents workflows from creating and approving pull-requests, and we can't set the correct setting automatically.

            ### Allowing workflows to create pull-requests

            You must explicitly allow GitHub Actions to create pull requests. This setting can be found in a repository's settings under `Actions > General > Workflow permissions`.
            
            For repositories belonging to an organization, this setting can be managed by admins in organization settings under `Actions > General > Workflow permissions`.

            That's it. You can close this issue now. 
            
            ---

            **Context**
            [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
            Workflow name - `${{ github.workflow }}`
            Job -           `${{ github.job }}`
            status -        `${{ job.status }}`
  